# Numpy

In [1]:
import numpy as np

## 1. 배열
numpy의 배열은 `numpy.ndarray`자료형이며, 행렬 계산시 매우 유용하다.

### 1.1. 배열의 생성

#### 1.1.1. `np.array()`
리스트를 `np.ndarray`로 변환하여 numpy 배열을 생성할 수 있다.

In [2]:
# 리스트를 np.ndarray로 변환하여 생성
a = np.array([1, 2, 3])
a

array([1, 2, 3])

#### 1.1.2. `np.arange()`
* 연속된 정수로 된 배열을 생성할 수 있다.
* 리스트에서 `range`를 이용해 연속된 정수로 된 배열을 생성하는 것과 비슷하다.
    * 시작과 끝을 정해서 특정 범위의 연속된 정수를 가진 배열을 생성할 수 있다.
    * 3번째 인수로 step을 주어서 +n씩 증가하는 연속된 정수를 가진 배열을 생성할 수 있다.

In [3]:
# 연속된 정수 생성
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 범위도 지정 가능 (시작 ~ 끝-1)
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [5]:
# step을 추가해서 +n식 증가시킬 수도 있음
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

#### 1.1.3. `np.zeros()`
모든 값이 0인 배열을 생성한다.

In [6]:
# 모든 값이 0으로 된 1차원 배열
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# 모든 값이 0으로 된 2차원 배열
a = np.zeros((3, 2))    # ()로 한 번 더 감싸주어야 한다 (위치니까)
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

#### 1.1.4. `np.ones()`
모든 값이 1인 배열을 생성한다.

In [8]:
# 모든 값이 1인 1차원 배열 생성
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [9]:
# 모든 값이 1인 2차원 배열 생성
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

#### 1.1.5. `np.full()`
모든 값이 특정 값으로 채워진 배열을 생성한다.
* `첫 번째 매개변수` : 배열의 크기  ex. `(2, 2)`, `5`
* `두 번째 매개변수` : 특정 값

In [10]:
# 특정 값으로 채워진 1차원 배열
a = np.full(5, 3)
a

array([3, 3, 3, 3, 3])

In [11]:
# 특정 값으로 채워진 2차원 배열
a = np.full((2, 3), 5)
a

array([[5, 5, 5],
       [5, 5, 5]])

#### 1.1.6. `np.eye()`와 `np.identity()`
매개변수로 `n`을 받았다고 할 때, `n*n`의 단위행렬을 생성한다.

In [12]:
# 대각선만 1로 채워지고 나머지는 0인 단위행렬을 생성
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 1.1.7. `np.empty_like()`
매개변수로 들어온 행렬과 같은 크기의 쓰레기값이 들어찬 빈 행렬을 생성한다.

In [14]:
a = np.arange(10).reshape(2, -1)
a, a.shape

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), (2, 5))

In [15]:
# a와 같은 크기의 빈 행렬 생성
b = np.empty_like(a)
b, b.shape

(array([[         0, 1072693248,          0, 1072693248,          0],
        [1072693248,          0, 1072693248,          0, 1072693248]]), (2, 5))

#### 1.1.8. `np.tile()`
* **첫번째 인자** : 복사할 대상 행렬
* **두번째 인자** : 행 그리고 열로 얼마만큼 복사할건지

In [16]:
a = np.arange(6).reshape(2, -1)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
# 아래로 3번, 옆으로 2번 동일한 행렬이 복사
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### 1.2. 랜덤 요소를 가진 배열의 생성

#### 1.2.1. seed 설정
seed값을 설정하여 난수 생성 시 동일한 난수가 나오도록 한다.      
후에 난수로 만든 배열을 여러 번 가공해야할 때가 있는데 그 때마다 난수가 달라지면 다시 처음부터 해야되기 때문이다.

In [18]:
# seed값 설정
np.random.seed(100)

#### 1.2.2. 랜덤 값을 가진 배열 생성

In [19]:
# 0과 1사이의 균등분포로 난수를 생성
np.random.rand(2, 3)

array([[0.54340494, 0.27836939, 0.42451759],
       [0.84477613, 0.00471886, 0.12156912]])

In [20]:
# 기댓값 0, 분산 1인 가우스분포로 난수를 생성
np.random.randn(2, 3)

array([[ 0.98132079,  0.51421884,  0.22117967],
       [-1.07004333, -0.18949583,  0.25500144]])

In [21]:
# (시작 ~ 끝-1)까지의 정수 중에서 난수를 생성
np.random.randint(1, 100, 5)

array([17, 10, 94, 87,  3])

In [22]:
# 정수 난수 2차원 배열 생성
np.random.randint(1, 100, (2, 3))

array([[28,  5, 32],
       [ 2, 14, 84]])

### 1.3. 배열의 특징
* `shape` : 배열의 크기
* `ndim` : 배열의 차원
* `len(배열)` : 배열의 길이 = 행의 개수
* `size` : 배열의 요소의 개수
* `dtype` : 배열의 요소의 자료형

In [23]:
a = np.random.randint(1, 100, (3, 4))

print('배열 a : \n', a)
print('='*30)
print('크기 :', a.shape)
print('차원 :', a.ndim)
print('길이 :', len(a))
print('요소 개수 :', a.size)
print('요소 자료형 :', a.dtype)

배열 a : 
 [[ 5 92 60 68]
 [ 8 50 48 66]
 [62 15 56 72]]
크기 : (3, 4)
차원 : 2
길이 : 3
요소 개수 : 12
요소 자료형 : int32


## 2. 배열 요소의 자료형

### 2.1. 자료형 지정
- `np.int32` : 32 비트 정수 타입
- `np.float64` : 64 비트 부동 소수 타입
- `np.complex` : 복소수 (128 float)
- `np.bool` : 불린 타입 (True, False)
- `np.object` : 파이썬 객체 타입
- `np.string_` : 고정자리 스트링 타입
- `np.unicode_` : 고정자리 유니코드 타입

In [24]:
# 배열 생성시 명시적으로 자료형을 알려줄 수 있음
a = np.array([1, 2, 3, 4], dtype=np.float64)
a, a.dtype

(array([1., 2., 3., 4.]), dtype('float64'))

### 2.2. 요소의 자료형변환
* **방법1** : `astype(원하는 자료형)`을 사용
* **방법2** : `np.원하는 자료형()`을 사용

In [25]:
a = np.random.rand(2, 3)
a

array([[0.17862432, 0.5325737 , 0.64669147],
       [0.14206538, 0.58138896, 0.47918994]])

In [26]:
# 방법 1 : astype()을 사용
b = a.astype(np.int32)
b

array([[0, 0, 0],
       [0, 0, 0]])

In [27]:
# 방법 2 : np.int32()을 사용
b = np.int32(a)
b

array([[0, 0, 0],
       [0, 0, 0]])

## 3. 배열 인덱싱

### 3.1. 슬라이싱
리스트 슬라이싱과 유사하지만, numpy 배열은 **다차원인 경우가 많**기 때문에 각 차원별로 어떻게 슬라이싱할건지 꼭 명시해야 한다.
* 슬라이싱해서 새로운 배열을 생성하는 것이 아니라 **원본 배열을 참조**하므로 슬라싱된 배열 수정시 원본 배열도 수정된다.
* `인덱싱+슬리이싱`을 사용하면 기존 배열보다 **한 차원 낮은 배열**이 추출된다.

In [28]:
a = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])
a, a.ndim

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), 2)

In [29]:
# 각 차원별로 어디서부터 어디까지 슬라이싱할건지 명시
b = a[:2, :2]
b, b.ndim

(array([[1, 2],
        [5, 6]]), 2)

In [30]:
# 슬라이싱된 배열은 원본 배열을 참조
id(a[0, 0]), id(b[0, 0])

(2361565201008, 2361565201008)

In [31]:
# 인덱싱과 슬라이싱 사용시 차원이 한 차원 낮아짐
c = a[:2, 2]
c, c.ndim

(array([3, 7]), 1)

### 3.2. 불리언 배열 인덱싱
특정 조건을 만족하는 요소만 추출할 때 쓰인다. 또한 추출된 요소를 수정하는 것도 가능하다!

In [32]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 원하는 조건의 인덱스
# 4보다는 크고 9보다는 작은 수
bool_idx = (a > 4) & (a < 9)
print(bool_idx)

a[bool_idx]

[[False False False]
 [False  True  True]
 [ True  True False]]


array([5, 6, 7, 8])

In [33]:
# 조건을 아에 인덱스 안에 넣어버려도 됨
a[(a > 4) & (a < 9)]

array([5, 6, 7, 8])

In [34]:
# 추출된 요소 수정도 가능
a[bool_idx] = 100
a

array([[  1,   2,   3],
       [  4, 100, 100],
       [100, 100,   9]])

## 4. 배열의 형태 변경
`reshape()`함수로 원하는 shape로 배열을 바꿀 수 있다!
* 다만, 바꿀 때 모든 배열의 요소가 들어가 있어야 한다.
* `-1`의 의미는 나머지 하나가 결정이 되면 요소의 개수에 따라 알아서 행과 열의 크기를 정한다는 것이다.

In [35]:
a = np.arange(10)
a, a.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (10,))

In [36]:
# (2, 5) 크기로 변경
b = a.reshape(2, 5)
b, b.shape

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), (2, 5))

In [37]:
# (2, -1) = (2, 5)랑 동일
# -1은 알아서 열의 크기를 계산
b = a.reshape(2, -1)
b, b.shape

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), (2, 5))

In [38]:
# numpy 배열의 reshape 메서드 말고 numpy 자체 reshape도 똑같이 적용 가능
# 첫번째 인수 : 대상 배열, 두번째 인수 : 변형 크기
c = np.reshape(a, (5, 2))
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [39]:
# -1로 알아서 나머지 행 또는 열의 크기 계산
c = np.reshape(a, (2, -1))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 5. 배열 연산

### 5.1. 요소별 연산

In [40]:
a = np.array([[1, 2],
              [3, 4]], dtype=np.float64)
b = np.array([[5, 6],
              [7, 8]], dtype=np.float64)

In [41]:
# 요소별 합
print(a+b, np.add(a, b), sep='\n')

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [42]:
# 요소별 차
print(a-b, np.subtract(a, b), sep='\n')

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [43]:
# 요소별 곱
print(a*b, np.multiply(a, b), sep='\n')

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [44]:
# 요소별 나눗셈
print(a/b, np.divide(a, b), sep='\n')

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [45]:
# 요소별 제곱근
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [46]:
# 요소별 지수
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [47]:
# 요소별 로그
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [48]:
# 요소별 반올림
c = np.log(a)
np.round(c, 2)

array([[0.  , 0.69],
       [1.1 , 1.39]])

### 5.2. 상수와의 연산

In [49]:
# 상수와의 곱
a * 10

array([[10., 20.],
       [30., 40.]])

In [50]:
# 상수와의 나눗셈
a / 4

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

### 5.3. 행렬의 곱 (내적)
* 행렬을 곱할 때는 `앞의 행렬의 열 == 뒤의 행렬의 행`이어야 한다.
* numpy에서는 **1차원 배열**을 **벡터**라고 인식하므로 행렬을 곱할 때 따로 크기를 변환하지 않아도 된다.

In [51]:
x = np.array([[1, 0, 1],
              [0, 1, 0]])
y = np.array([[1, 2],
              [3, 4],
              [5, 6]])
z = np.array([-1, 0, -1])
w = np.array([1, 2, 3])

x.shape, y.shape, z.shape

((2, 3), (3, 2), (3,))

In [52]:
# 행렬과 행렬의 곱
# 앞 행렬의 열 == 뒤 행렬의 행
print(x.dot(y), np.dot(x, y), sep='\n')

[[6 8]
 [3 4]]
[[6 8]
 [3 4]]


In [53]:
# 행렬과 벡터의 곱
# 행렬의 열 == 벡터의 크기
print(x.dot(z), np.dot(x, z), sep='\n')

[-2  0]
[-2  0]


In [54]:
# 벡터와 벡터의 곱
# 앞 벡터의 크기 == 뒤 벡터의 크기
print(z.dot(w), np.dot(z, w), sep='\n')

-4
-4


### 5.4. 연산과 관련된 함수 

In [55]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

#### 5.4.1. 행렬의 axis
* `axis=None` : 행렬 전체
* `axis=0` : 행렬의 각각의 열
* `axis=1` : 행렬의 각각의 행

#### 5.4.2. `np.sum()`

In [56]:
print(np.sum(a))           # 전체 요소의 합
print(np.sum(a, axis=0))   # 각 열의 요소의 합
print(np.sum(a, axis=1))   # 각 행의 요소의 합

21
[5 7 9]
[ 6 15]


#### 5.4.3. `np.mean()`

In [57]:
print(np.mean(a))         # 전체 요소의 평균
print(np.mean(a, axis=0)) # 각 열의 요소의 평균
print(np.mean(a, axis=1)) # 각 행의 요소의 평균

3.5
[2.5 3.5 4.5]
[2. 5.]


#### 5.4.4. `np.std()`

In [58]:
print(np.std(a))          # 전체 요소의 표준편차
print(np.std(a, axis=0))  # 각 열의 요소의 표준편차
print(np.std(a, axis=1))  # 각 행의 요소의 표준편차

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


#### 5.4.5. `np.max()`

In [59]:
print(np.max(a))          # 전체 요소의 최대값 
print(np.max(a, axis=0))  # 각 열의 요소의 최대값 
print(np.max(a, axis=1))  # 각 행의 요소의 최대값

6
[4 5 6]
[3 6]


#### 5.4.6. `np.min()`

In [60]:
print(np.min(a))          # 전체 요소의 최소값 
print(np.min(a, axis=0))  # 각 열의 요소의 최소값 
print(np.min(a, axis=1))  # 각 행의 요소의 최소값

1
[1 2 3]
[1 4]


#### 5.4.7. `np.argmin()`, `np.argmax()`

In [61]:
print(np.argmin(a))          # 전체 요소의 최소값의 위치
print(np.argmin(a, axis=0))  # 각 열의 요소의 최소값의 위치 
print(np.argmin(a, axis=1))  # 각 행의 요소의 최소값의 위치

print(np.argmax(a))          # 전체 요소의 최대값의 위치
print(np.argmax(a, axis=0))  # 각 열의 요소의 최대값의 위치 
print(np.argmax(a, axis=1))  # 각 행의 요소의 최대값의 위치

0
[0 0 0]
[0 0]
5
[1 1 1]
[2 2]


#### 5.4.8. `np.where`
특정 조건을 만족하는 요소의 인덱스를 반환한다.     
* 불리언 인덱싱은 해당 행렬의 크기만큼 `True/False`로 채워져 있으며 `np.where`은 해당 요소들의 인덱스를 반환한다.
* 반환 시 위치를 튜플로 반환을 하는데, 여러 개의 요소가 있을 경우 튜플에 첫 번째에 해당 요소의 `행` 리스트가, 두 번째에 해당 요소의 `열` 리스트가 반환된다.

In [62]:
a = np.arange(10).reshape(2, -1)
print('행렬 : \n', a)
print('='*50)

# 4보다 크고 8보다 작은 요소들의 인덱스
# 튜플로 반환이 되는데 첫번째 것이 행이고
# 두번째 것이 열이다 -> 조합하면 위치
idx = np.where((a>2)&(a<8))
print('인덱스 :', idx, '\n추출 :', a[idx])

행렬 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
인덱스 : (array([0, 0, 1, 1, 1], dtype=int64), array([3, 4, 0, 1, 2], dtype=int64)) 
추출 : [3 4 5 6 7]


#### 5.4.9. 행렬의 전치
* `T`라는 변수는 해당 배열의 전치 행렬을 저장하고 있다.
* 전치 시 대각선을 기준으로 행과 열을 바꾼다.
* 1차원 행렬의 경우 전치시 아무 일도 일어나지 않는다.

In [63]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[1, -2],
              [-3, 4]])
              
a.shape, b.shape

((2, 3), (2, 2))

In [64]:
# 각각의 행렬을 전치
print('a의 전치 :\n', a.T, '\nb의 전치 :\n', b.T)
a.T.shape, b.T.shape

a의 전치 :
 [[1 4]
 [2 5]
 [3 6]] 
b의 전치 :
 [[ 1 -3]
 [-2  4]]


((3, 2), (2, 2))

In [65]:
# 1차원 행렬을 전치할 경우 아무 일도 일어나지 않는다
c = np.arange(10)
c, c.T

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

### 5.5. 배열 비교 연산

In [66]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[1, 1, 1],
              [4, 5, 3]])
c = np.array([[1, 2, 3],
              [4, 5, 6]])

#### 5.5.1. 배열 요소별 비교 (element-wise)
크기가 다르면 에러를 발생시키므로 같은 크기의 행렬끼리 비교가 가능하다.

In [67]:
# 각각의 요소가 같은지 비교
a == b

array([[ True, False, False],
       [ True,  True, False]])

In [68]:
# 각각의 요소가 a가 b보다 큰지 비교
# 내가 아는 비교 연산자 다 사용가능
a > b

array([[False,  True,  True],
       [False, False,  True]])

#### 5.5.2. 배열 전체 비교 (array-wise)

배열의 크기, 요소 모두가 같은지를 확인한다.

In [69]:
# 다르면 False
np.array_equal(a, b)

False

In [70]:
# 같으면 True
np.array_equal(a, c)

True

## 6. 배열 복사
우리가 인덱싱, 슬라이싱하여 반환되는 행렬은 새로 생성되는 행렬 객체가 아니라 기존의 행렬이다. 즉, **참조**를 하는 것.    
그래서 우리가 참조한 부분 행렬들을 변형시킬 경우 원본 행렬이 변할 수 있다. 만약 원본은 훼손하고 싶지 않다면 **새로운 행렬 객체를 생성**해주어야 한다.

In [71]:
a = np.array([1, 2, 3])
b = a
c = np.copy(a)

id(a), id(b), id(c)

(2361565462976, 2361565462976, 2361565463136)

## 7. 브로드캐스팅
**`shape`가 다른 행렬 간의 요소별 연산**을 가능케 하는 것이다.    
큰 행렬과 작은 행렬이 있을 때 큰 행렬을 대상으로 작은 행렬을 여러 번 연산하고 싶을 때 브로드캐스팅이 적용된다.
* `상황1` : 각 차원(행, 열)의 요소수가 동일한 경우   
<img src='broadcast2.png' width=250px>  

* `상황2` : 둘 중 하나의 차원의 요소수가 1인 경우      
<img src='broadcast1.png' width=250px>

In [72]:
x = np.arange(12).reshape(3, -1)
y = np.array([1, 2, 3]).reshape(-1, 1)

print('행렬 x: \n', x, '\n행렬 y: \n', y)

행렬 x: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
행렬 y: 
 [[1]
 [2]
 [3]]


In [73]:
# 작은 행렬이 큰 행렬에 맞추어 확장된다
x+y

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [74]:
# 상수(스칼라)도 하나의 행렬이므로 큰 행렬에 맞춰 확장된다
x+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [75]:
# 열 벡터(m*1)과 행 벡터(n*1)를 연산을 하면 (m*n) 벡터가 된다
a = np.arange(5).reshape(-1, 1)
b = np.arange(3)

a*b

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6],
       [0, 4, 8]])

## 8. 배열 결합

In [76]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[7,   8,   9],
              [10, 11, 12]])

### 8.1. `np.concatenate()`
* **첫번째 인자** : 결합하려는 행렬들을 묶은 튜플
* **두번째 인자** : 결합 방향(기본은 `axis=0`)

In [77]:
# axis=0 열, 아래 방향으로 결함
np.concatenate((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
# axis=1 행, 옆 방향으로 결합
np.concatenate((a, b), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### 8.2. `np.c_[,]`와 `np.r_[,]`
* 좌우 결합 : `np.c_[a, b]` == `np.concatenate((a,b), axis=1)`
* 상하 결합 : `np.r_[a, b]` == `np.concatenate((a,b))`

In [79]:
# 상하결합, axis=0
np.r_[a,b]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [80]:
# 좌우결합, axis=1
np.c_[a,b]

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## 9. 파일 저장
### 9.1. 하나의 `ndarray`형을 저장

In [81]:
x = np.arange(10).reshape(-1, 5)
print(x)

# 세이브
np.save('filesave_single.npy', x)

# 현재 이 셀의 x 데이터 삭제
x = []

# 로드
x = np.load('filesave_single.npy')
x

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 9.2. 여러 개의 `ndarray`형을 저장

In [82]:
a = np.arange(15).reshape(3, -1)
b = np.eye(3)
c = np.ones((2, 2))
print('부르기 전', '='*30, '\na =\n', a, '\nb =\n', b, '\nc =\n', c)

# 세이브 (뒤에는 key값 설정하는 것이라 생각)
np.savez('filesave_several.npz', a=a, b=b, c=c)

# 현재 이 셀의 a, b, c 데이터 삭제
a = []; b = []; c = []

# 로드
file = np.load('filesave_several.npz')
a = file['a']
b = file['b']
c = file['c']

print('불러운 후','='*30, '\na =\n', a, '\nb =\n', b, '\nc =\n', c)

부르기 전 ============================== 
a =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 
b =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
c =
 [[1. 1.]
 [1. 1.]]
불러운 후 ============================== 
a =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 
b =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
c =
 [[1. 1.]
 [1. 1.]]


## 10. Help (도움말)
어떤 함수의 사용법을 모를 때 `help()`를 이용해 사용법을 알아낼 수 있다.

In [83]:
help(np.sqrt)

Help on ufunc object:

sqrt = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array 