# Numpy Practice 2
본격적인 데이터 분석에 들어가기 전에 `numpy`를 이용하여 간단한 데이터 처리를 해봅시다!

In [1]:
import numpy as np

## 1. `student.csv` 설명
학생들의 총점은 **출석 10%, 중간 40%, 기말 40%, 과제1, 2 각각 5%**로 계산된다.

이 때 각 column의 의미하는 바는 다음과 같다.
* `id` : 학생들을 구분하는 id
* `present/absent/late` : 출석/결석/지각 수 (총 32일)
* `midterm/final` : 중간고사/기말고사 성적 (100점 만점)
* `assignment1/assignemnt2` : 과제1, 2 성적 (10점 만점)

## 2. 파일 불러오기

In [2]:
data = np.loadtxt('./student.csv', delimiter=',')
data

array([[ 1., 32.,  0.,  0., 60., 20., 10., 10.],
       [ 2., 20., 10.,  2., 75., 28., 10., 10.],
       [ 3., 10.,  2., 20., 24., 24., 10.,  7.],
       [ 4., 30.,  1.,  1., 87., 29., 10.,  8.],
       [ 5., 31.,  0.,  1., 56., 31.,  8.,  7.],
       [ 6., 29.,  3.,  0., 93., 19.,  9.,  6.],
       [ 7.,  1., 30.,  1., 32., 43., 10., 10.],
       [ 8., 28.,  2.,  2., 56., 30., 10., 10.],
       [ 9., 32.,  0.,  0., 29., 50., 10., 10.],
       [10., 31.,  1.,  0., 74., 35.,  0., 10.],
       [11., 27.,  1.,  4., 81., 42.,  0., 10.],
       [12., 26.,  2.,  4., 76., 22.,  0., 10.],
       [13., 22.,  6.,  4., 83., 19., 10.,  6.],
       [14., 31.,  1.,  0., 75.,  5.,  9., 10.],
       [15., 19.,  1., 12., 76., 11.,  8., 10.],
       [16., 28.,  0.,  4., 81., 36.,  7.,  1.],
       [17., 32.,  0.,  0., 77., 30.,  5., 10.],
       [18.,  0.,  0., 32., 71., 29.,  5., 10.],
       [19., 29.,  1.,  2., 74., 21., 10.,  9.],
       [20., 23.,  2.,  7., 69., 31., 10.,  7.]])

## 3. 연습문제

### 3.1. student 데이터의 위의 다섯 개의 행을 출력하시오.

In [3]:
data[:5,:]

array([[ 1., 32.,  0.,  0., 60., 20., 10., 10.],
       [ 2., 20., 10.,  2., 75., 28., 10., 10.],
       [ 3., 10.,  2., 20., 24., 24., 10.,  7.],
       [ 4., 30.,  1.,  1., 87., 29., 10.,  8.],
       [ 5., 31.,  0.,  1., 56., 31.,  8.,  7.]])

### 3.2. student 데이터의 크기를 확인하시오.

In [4]:
data.shape

(20, 8)

### 3.3. 각 학생들의 총 점수를 1차원 배열로 나타내시오.

#### 3.3.1. 출석과 관련된 부분만 슬라이싱 하시오.

In [5]:
data[:, 1:4]

array([[32.,  0.,  0.],
       [20., 10.,  2.],
       [10.,  2., 20.],
       [30.,  1.,  1.],
       [31.,  0.,  1.],
       [29.,  3.,  0.],
       [ 1., 30.,  1.],
       [28.,  2.,  2.],
       [32.,  0.,  0.],
       [31.,  1.,  0.],
       [27.,  1.,  4.],
       [26.,  2.,  4.],
       [22.,  6.,  4.],
       [31.,  1.,  0.],
       [19.,  1., 12.],
       [28.,  0.,  4.],
       [32.,  0.,  0.],
       [ 0.,  0., 32.],
       [29.,  1.,  2.],
       [23.,  2.,  7.]])

#### 3.3.2. 출석 점수를 계산하여 `attend`라는 1차원 배열에 저장하시오.
* 출석 일수는 총 32이다.
* 지각 한 번당 -0.5, 결석 한 번당 -1점 감점이 된다.
* 감점이 -4이상으로 되면 출석 점수를 0점 처리한다.
* 출석 점수는 반영비율이 10%이다.

In [16]:
attend = 32 + data[:, 2:4].dot(np.array([-1, -0.5]))
attend[attend <= 28] = 0
attend = attend/32*10
attend

array([10.     ,  0.     ,  0.     ,  9.53125,  9.84375,  9.0625 ,
        0.     ,  9.0625 , 10.     ,  9.6875 ,  9.0625 ,  0.     ,
        0.     ,  9.6875 ,  0.     ,  9.375  , 10.     ,  0.     ,
        9.375  ,  0.     ])

#### 3.3.3. 중간고사, 기말고사와 관련된 부분만 슬라이싱 하시오.

In [17]:
data[:, [4, 5]]

array([[60., 20.],
       [75., 28.],
       [24., 24.],
       [87., 29.],
       [56., 31.],
       [93., 19.],
       [32., 43.],
       [56., 30.],
       [29., 50.],
       [74., 35.],
       [81., 42.],
       [76., 22.],
       [83., 19.],
       [75.,  5.],
       [76., 11.],
       [81., 36.],
       [77., 30.],
       [71., 29.],
       [74., 21.],
       [69., 31.]])

#### 3.3.4. 시험 점수를 계산하여 `exam`라는 1차원 배열에 저장하시오.
* 중간고사 반영비율은 40%, 기말고사 반영비율은 40%이다.
* 중간고사, 기말고사 모두 총점이 100점 만점이다.

In [18]:
exam = data[:, [4, 5]].dot(np.array([0.4, 0.4]))
exam

array([32. , 41.2, 19.2, 46.4, 34.8, 44.8, 30. , 34.4, 31.6, 43.6, 49.2,
       39.2, 40.8, 32. , 34.8, 46.8, 42.8, 40. , 38. , 40. ])

#### 3.3.5. 과제와 관련된 부분만 슬라이싱 하시오.

In [19]:
data[:, [-2, -1]]

array([[10., 10.],
       [10., 10.],
       [10.,  7.],
       [10.,  8.],
       [ 8.,  7.],
       [ 9.,  6.],
       [10., 10.],
       [10., 10.],
       [10., 10.],
       [ 0., 10.],
       [ 0., 10.],
       [ 0., 10.],
       [10.,  6.],
       [ 9., 10.],
       [ 8., 10.],
       [ 7.,  1.],
       [ 5., 10.],
       [ 5., 10.],
       [10.,  9.],
       [10.,  7.]])

#### 3.3.6. 과제 점수를 계산하여 `assignment`라는 1차원 배열에 저장하시오.
* 과제 1, 2는 모두 총점이 10점 만점이다.
* 과제 1, 2의 반영비율은 각각 5%이다.

In [20]:
assignment = data[:, [-2, -1]].dot(np.array([0.5, 0.5]))
assignment

array([10. , 10. ,  8.5,  9. ,  7.5,  7.5, 10. , 10. , 10. ,  5. ,  5. ,
        5. ,  8. ,  9.5,  9. ,  4. ,  7.5,  7.5,  9.5,  8.5])

#### 3.3.7. 각 학생들의 총점을 `result`라는 1차원 배열에 저장하시오.

In [21]:
result = attend+exam+assignment
result

array([52.     , 51.2    , 27.7    , 64.93125, 52.14375, 61.3625 ,
       40.     , 53.4625 , 51.6    , 58.2875 , 63.2625 , 44.2    ,
       48.8    , 51.1875 , 43.8    , 60.175  , 60.3    , 47.5    ,
       56.875  , 48.5    ])

#### 3.3.8. 학생들의 평균을 `avg`, 표준편차를 `std`, 최고점수를 `max_score`, 최저점수를 `min_score`에 저장하시오. 

In [22]:
avg = np.mean(result)
std = np.std(result)
max_score = np.max(result)
min_score = np.min(result)

print('평균 :', avg)
print('표준편차 :', std)
print('최고점수 :', max_score)
print('최저점수 :', min_score)

평균 : 51.864374999999995
표준편차 : 8.629305560305822
최고점수 : 64.93125
최저점수 : 27.700000000000003
